# GitBook configuration for Bodega Auth Service (TypeScript)
root: ./README.md
summary: ./SUMMARY.md

# Optional: Add metadata, plugins, or customizations below as needed
# For example:
# title: Bodega Auth Service TS Documentation
# plugins:
#   - search
#   - highlight
